# --- General options --- #

# url is the full website URL
# baseurl is the website's URL without the hostname

# If you are building a simple GitHub user page (http://username.github.io) then use these settings:
url: "https://www.mpi-forum.org"
baseurl: ""

# If you are building a GitHub project page then use these settings:
#url: "http://username.github.io/projectname"
#baseurl: "/projectname"

# Of course don't forget to change the username and projectname to YOUR username and project
#repository: https://github.com/mpi-forum/mpi-forum.github.io

# Name of website
title: MPI Forum

# Short description of your site
description: This website contains information about the activities of the MPI Forum, which is the standardization forum for the Message Passing Interface (MPI).

# --- Navigation bar options --- #

# List of links in the navigation bar
navbar-links:
    Docs: "docs/"
    Current MPI Efforts:
        - Implementation Status: implementation-status/
        - MPI Next: "mpi-next/"
    Meetings:
        - Voting Meetings: "meetings"
        - Non-Voting Meetings: "non_voting_meetings"
    Resources:
        - New to the MPI Forum: "new/"
        - GitHub: "https://www.github.com/mpi-forum/"
        - Mailing Lists: "http://lists.mpi-forum.org"
        - Make Comments: "comments/"
        - Past Efforts: "mpi-past/"

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
# avatar: "/img/avatar-icon.png"

# --- Misc --- #

# Fill in your Google Analytics ID to track your website using GA
google_analytics: "UA-110855000-1"

# --- Don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "America/Chicago"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: false  # add comments to all blog posts
      social-share: false # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: false

safe: true

whitelist:
  - jekyll-redirect-from

plugins:
  - jekyll-redirect-from

# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189
